#ifndef PARAM_GERAL_H
#define PARAM_GERAL_H

#define MAXARCSIZE 300 
#define PROFUNDIDADEGRID 5 
#define NUM_AVALIACOES 1000000

#define TAMANHOPOPULACAO_NSGAII 300  // tamanho da populaçao
#define TAXADECRUZAMENTO 0.90 // (IRACE para o NSGA-II)
#define TAXADEMUTACAO 0.07 // (IRACE para o NSGA-II)


///// IRACE
#define NUMSUMPROBLEMAS 78 
#define NUM_VIZINHOS  12 
#define MAX_SUB_POPULATION 18 



#endif